### PR TITLE
Fix bug that received field masks from the frontend are not compatible with the field masks from the mock backend

### LINKED ISSUE #59: [Bug]: Field masks not compatible with backend
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Which use case does this bug relate to?

SE-UUlm/snowballr-backend#31

### What happened?

When I use the latest version of the frontend to change my name (first name or last name, doesn't matter), then the backend responds with an error, although the new name is valid. This is because the interpretation of the field mask in the backend is different than in the frontend and mock backend.

The frontend was updated to be compatible with the backend, but the mock backend need to be updated as well.

### Steps to reproduce

1. Open the frontend and go to the user settings.
2. Change your name to a valid new name.
3. Submit the request to the mock backend.

### What did you expect?

The mock backend should interpret the field mask the same way as the frontend and backend.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Merseleo**
Closes #59

- I added a helper function `generateUpdateObject` to parse the field masks and generate the update objects

### CODE REVIEW

File: src/util.ts [hunk 1]
```diff
@@ -250,3 +252,39 @@ export function getProjectPaperData(paperId: Id): PaperInProjectResult | undefin
...
+    mask?: FieldMask,
+    prefix?: string,
+): WithFieldMask<T> {
+    const prefixToDelete = prefix ? `${prefix}.` : "";
+
+    const parsedFieldMask =
+        mask?.paths
+            .filter((p) => p.startsWith(prefixToDelete))
+            .map((p) => p.slice(prefixToDelete.length))
+            .map((path) => path.split(".").filter(Boolean).map(snakeToCamelCase).join(".")) ?? [];
```
Comment (mowi12) [inline src/util.ts:285]: Please add a comment either inline or in the documentation of the function.

File: src/util.ts [hunk 2]
```diff
@@ -250,3 +252,39 @@ export function getProjectPaperData(paperId: Id): PaperInProjectResult | undefin
...
+ * Applies a FieldMask object to a given object and build a partial object.
+ *
+ * Optionally, remove a prefix from the field names.
+ *
+ * @param obj - The object for which the field mask should be applied.
+ * @param prefix - An optional string prepended to each field path and should be deleted.
+ */
+export function generateUpdateObject<T>(
+    obj: T,
+    mask?: FieldMask,
```
Comment (mowi12) [inline src/util.ts:274]: Please add the mask parameter to the documentation of the function.

**Review by mowi12 — CHANGES_REQUESTED** [review]
Nicely done! The logic seems to be working!

Only some documentation mishaps : )

Also, please fix line 591 in the `service.ts` file.

**Review by mowi12 — APPROVED** [review]
Looks good now : )
