### PR TITLE
fix/46 change parameters of get next or previous paper

### LINKED ISSUE #46: [FIX]: Change the processing of the `paperId`
At the moment the processing of the `paperId` to get the next or previous paper depends on the following structure: `{projectId}-{paperId}`. Because the ids are not of this from anymore the backend has to adjust the processing of the `paperId`.

### PR DESCRIPTION
**Pull request by domienderle**
Closes #46 

## What I have made

Due to the fact, that the mock-backend don't habe relations from a `ProjectPaper` to the according `Project` (which will be implemented in the real backend), I have added a loop, that searches for the `Project` the `ProjectPaper` is part of (to implemente the methods `getNextPaper()`, `getNextPaperToReview()` and `getPreviousPaper()` correctly). Thus, it is possible to determine the `ProjectPapers` project without supplying it via the method parameters.

### CODE REVIEW

File: src/service.ts [hunk 1]
```diff
@@ -1393,14 +1393,15 @@ export const snowballRService: ISnowballR = {
         call: ServerUnaryCall<Id, Project_Paper>,
         callback: sendUnaryData<Project_Paper>,
     ): void {
-        const { projectPaper, projectPapers } = getProjectPaperData(call.request);
-        if (!projectPaper) {
+        const result = getProjectPaperData(call.request.id);
+        if (!result) {
             callback({
                 code: status.NOT_FOUND,
                 message: "Paper with the given id was not found",
```
Comment (mowi12) [inline src/service.ts:1400]: I think the last time I reviewed the implementation of these calls, I may not have checked the error messages. Are you sure you want to return 'Paper with the give id was not found' here, but in the next call (getNextPaperToReview) you want to return 'no next paper available'? This seems a bit inconsistent or am I completely misunderstanding the getNextPaper method?

Comment (mowi12) [reply src/service.ts:1400]: I think I understood it now. But just to double check, I will keep this conversation for you to take a look at.

File: src/util.ts [hunk 2]
```diff
@@ -226,21 +226,26 @@ export function makeResponseAuthMetadata(tokenPair: TokenPair): Metadata {
...
 
 /**
- * Searches for the project paper with the given id, the according project and its project papers.
+ * Searches for the project paper with the given id and its project papers.
  *
- * @param paperId the id of the paper that should be found.
+ * @param paperId the id of the project papers project
  * @returns PaperInProjectResult
  */
-export function getProjectPaperData(paperId: Id): PaperInProjectResult {
```
Comment (mowi12) [inline src/util.ts:239]: Any reason why you changed the signature? This know you have to always use the `.id` ending if you want to call this method. Before this only had to be done inside this method and therefore only once instead of everytime you want to call this method.

File: src/util.ts [hunk 3]
```diff
@@ -226,21 +226,26 @@ export function makeResponseAuthMetadata(tokenPair: TokenPair): Metadata {
...
 interface PaperInProjectResult {
     projectId: string;
-    projectPaper?: Project_Paper;
+    projectPaper: Project_Paper;
     projectPapers: Project_Paper[];
 }
 
 /**
- * Searches for the project paper with the given id, the according project and its project papers.
+ * Searches for the project paper with the given id and its project papers.
```
Comment (mowi12) [inline src/util.ts:234]: 'Searches for the PROJECT PAPER with the given id and its PROJECT PAPERS'. This doesn't make any sense, or does it?

File: src/util.ts [hunk 4]
```diff
@@ -226,21 +226,26 @@ export function makeResponseAuthMetadata(tokenPair: TokenPair): Metadata {
...
  *
- * @param paperId the id of the paper that should be found.
+ * @param paperId the id of the project papers project
```
Comment (mowi12) [inline src/util.ts:236]: 'paperId' -> project papers project? What is that?

File: src/util.ts [hunk 5]
```diff
@@ -226,21 +226,26 @@ export function makeResponseAuthMetadata(tokenPair: TokenPair): Metadata {
...
+    for (const project of PROJECTS.values()) {
+        const projectId = project.id;
+        const projectPapers = PROJECT_PROJECT_PAPERS.get(projectId)!
+            .map((ppp) => PROJECT_PAPERS.get(ppp)!)
+            .map(addProjectPaperReviews);
+        const projectPaper = projectPapers.find((pp) => pp.id === paperId);
+        if (projectPaper) {
+            return { projectId, projectPaper, projectPapers };
+        }
+    }
```
Comment (mowi12) [inline src/util.ts:249]: Why exactly do you iterate over all projects? Doesn't a project paper always belong to a specific project and if we want the next paper/previous paper why do we search in all?

And if this is only to search, the `find()` is the way to go, or not?

**Review by mowi12 — CHANGES_REQUESTED** [review]
I'm sorry, but I do not quite understand this implementation. Could you please explain it to me?

File: src/util.ts (hunk 3 above)
Comment (domienderle) [reply src/util.ts:234]: True. Is changed.

File: src/util.ts (hunk 4 above)
Comment (domienderle) [reply src/util.ts:236]: Same. Is changed.

File: src/util.ts (hunk 5 above)
Comment (domienderle) [reply src/util.ts:249]: I have to iterate over all projects, because the mock-backend doesn't support the functionality to get its according `projectId`. This will be implemented by the backend, so this is just a workaround.

I have tried to implement it more functional, but this would only make the code longer and more complex to read.

**Review by mowi12 — APPROVED** [review]
Thanks for explaining and updating the comments. Everything looks fine now!
